# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forwarder < Formula
  desc "Fast HTTP(S) proxy with PAC support"
  homepage "https://github.com/saucelabs/forwarder"
  version "1.0.2"
  license "MPL-2.0"

  on_macos do
    url "https://github.com/saucelabs/forwarder/releases/download/v1.0.2/forwarder-1.0.2_darwin.all.zip"
    sha256 "e58bfce78820b0e060b699747ac0f143f2b6e3233143b941ca04ae66a28a14e5"

    def install
      bin.install "forwarder"
      bash_completion.install "completions/forwarder.bash" => "forwarder"
      zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
      fish_completion.install "completions/forwarder.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saucelabs/forwarder/releases/download/v1.0.2/forwarder-1.0.2_linux.aarch64.tar.gz"
      sha256 "bd4743fc35f82c000a8694848f5f11db23f12fa1a0d6d7486ec6d070102281fd"

      def install
        bin.install "forwarder"
        bash_completion.install "completions/forwarder.bash" => "forwarder"
        zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
        fish_completion.install "completions/forwarder.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/saucelabs/forwarder/releases/download/v1.0.2/forwarder-1.0.2_linux.x86_64.tar.gz"
      sha256 "f5506a67347f7e7296b3f8d853349d32573497d668dbc7145aa01e580debf103"

      def install
        bin.install "forwarder"
        bash_completion.install "completions/forwarder.bash" => "forwarder"
        zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
        fish_completion.install "completions/forwarder.fish"
      end
    end
  end

  test do
    system "#{bin}/forwarder version"
  end
end
