# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forwarder < Formula
  desc "Fast HTTP(S) proxy with PAC support"
  homepage "https://github.com/saucelabs/forwarder"
  version "1.0.3"
  license "MPL-2.0"

  on_macos do
    url "https://github.com/saucelabs/forwarder/releases/download/v1.0.3/forwarder-1.0.3_darwin.all.zip"
    sha256 "5efec9e927038c3a245402f5fa450bc469704e4e32e653d468356e3b09ee81e1"

    def install
      bin.install "forwarder"
      bash_completion.install "completions/forwarder.bash" => "forwarder"
      zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
      fish_completion.install "completions/forwarder.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saucelabs/forwarder/releases/download/v1.0.3/forwarder-1.0.3_linux.aarch64.tar.gz"
      sha256 "c0ab5b9e312887046c82f6a4d227284765d1a4629c78c845f31abcf45ea3a29e"

      def install
        bin.install "forwarder"
        bash_completion.install "completions/forwarder.bash" => "forwarder"
        zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
        fish_completion.install "completions/forwarder.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/saucelabs/forwarder/releases/download/v1.0.3/forwarder-1.0.3_linux.x86_64.tar.gz"
      sha256 "19c2fdc9a0a8422b8549d6fb506b8a901583f6417f2a1a80fcb1f010887d09dc"

      def install
        bin.install "forwarder"
        bash_completion.install "completions/forwarder.bash" => "forwarder"
        zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
        fish_completion.install "completions/forwarder.fish"
      end
    end
  end

  test do
    system "#{bin}/forwarder version"
  end
end
