# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forwarder < Formula
  desc "Forward MITM proxy with PAC support"
  homepage "https://opensource.saucelabs.com/forwarder/"
  version "1.4.0"
  license "MPL-2.0"

  on_macos do
    url "https://github.com/saucelabs/forwarder/releases/download/v1.4.0/forwarder-1.4.0_darwin.all.zip"
    sha256 "405e804eb8aba94186361369aaf8e6fc3911b334603e5bcac4429c458f749884"

    def install
      bin.install "forwarder"
      bash_completion.install "completions/forwarder.bash" => "forwarder"
      zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
      fish_completion.install "completions/forwarder.fish"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saucelabs/forwarder/releases/download/v1.4.0/forwarder-1.4.0_linux.x86_64.tar.gz"
        sha256 "415dbf5753219632edb79ff0ba083004347fd084bbc9fc65a5caa5d7d2d14695"

        def install
          bin.install "forwarder"
          bash_completion.install "completions/forwarder.bash" => "forwarder"
          zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
          fish_completion.install "completions/forwarder.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/saucelabs/forwarder/releases/download/v1.4.0/forwarder-1.4.0_linux.aarch64.tar.gz"
        sha256 "5510194ed61c09704442c18ec89566559ef981f3159ae6da1c771cc2c2926eb5"

        def install
          bin.install "forwarder"
          bash_completion.install "completions/forwarder.bash" => "forwarder"
          zsh_completion.install "completions/forwarder.zsh" => "_forwarder"
          fish_completion.install "completions/forwarder.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/forwarder version"
  end
end
