# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SauceConnect < Formula
  desc "Sauce Connect Proxy"
  homepage "https://docs.saucelabs.com/secure-connections/sauce-connect-5/"
  version "5.1.0"
  license "Proprietary"

  on_macos do
    url "https://saucelabs.com/downloads/sauce-connect/5.1.0/sauce-connect-5.1.0_darwin.all.zip"
    sha256 "e587d5a9b5e5c928600d9e5e35d74ae9926218c7e13ab1da90f26da411d360cd"

    def install
      bin.install "sc"
      bash_completion.install "completions/sc.bash" => "sc"
      zsh_completion.install "completions/sc.zsh" => "_sc"
      fish_completion.install "completions/sc.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://saucelabs.com/downloads/sauce-connect/5.1.0/sauce-connect-5.1.0_linux.aarch64.tar.gz"
      sha256 "69ef7830b8ea3fc2bd9129cbf3f5ff04a22c6a7cd8a3c9e1e1ff0ee411b0ca20"

      def install
        bin.install "sc"
        bash_completion.install "completions/sc.bash" => "sc"
        zsh_completion.install "completions/sc.zsh" => "_sc"
        fish_completion.install "completions/sc.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://saucelabs.com/downloads/sauce-connect/5.1.0/sauce-connect-5.1.0_linux.x86_64.tar.gz"
      sha256 "a8263808944a4aa87af11ac12fb41e740b41f001a113d01a4ee8dfae17a018c2"

      def install
        bin.install "sc"
        bash_completion.install "completions/sc.bash" => "sc"
        zsh_completion.install "completions/sc.zsh" => "_sc"
        fish_completion.install "completions/sc.fish"
      end
    end
  end

  test do
    system "#{bin}/sc version"
  end
end
