# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SauceConnect < Formula
  desc "Sauce Connect Proxy"
  homepage "https://docs.saucelabs.com/secure-connections/sauce-connect-5/"
  version "5.5.0"
  license "Proprietary"

  on_macos do
    url "https://saucelabs.com/downloads/sauce-connect/5.5.0/sauce-connect-5.5.0_darwin.all.zip"
    sha256 "7fc8237c3455704592188c4946083a13878d99b327362140df41a4e937e0e26f"

    def install
      bin.install "sc"
      bash_completion.install "completions/sc.bash" => "sc"
      zsh_completion.install "completions/sc.zsh" => "_sc"
      fish_completion.install "completions/sc.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://saucelabs.com/downloads/sauce-connect/5.5.0/sauce-connect-5.5.0_linux.x86_64.tar.gz"
        sha256 "a986a49374636ecafca5aa6517157fb187c1b93b90f719cc0668c5406534cd48"

        def install
          bin.install "sc"
          bash_completion.install "completions/sc.bash" => "sc"
          zsh_completion.install "completions/sc.zsh" => "_sc"
          fish_completion.install "completions/sc.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://saucelabs.com/downloads/sauce-connect/5.5.0/sauce-connect-5.5.0_linux.aarch64.tar.gz"
        sha256 "21267e27fadd5a9ed58cb2d92469e886616beea41a61bda57300d95e103552d3"

        def install
          bin.install "sc"
          bash_completion.install "completions/sc.bash" => "sc"
          zsh_completion.install "completions/sc.zsh" => "_sc"
          fish_completion.install "completions/sc.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/sc version"
  end
end
