# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SauceConnect < Formula
  desc "Sauce Connect Proxy"
  homepage "https://docs.saucelabs.com/secure-connections/sauce-connect-5/"
  version "5.0.1"
  license "Proprietary"

  on_macos do
    url "https://saucelabs.com/downloads/sauce-connect/5.0.1/sauce-connect-5.0.1_darwin.all.zip"
    sha256 "53e8df165488a92ef5fdb2c0ede76aca6ccda3ac735677923a28ba6904ce56eb"

    def install
      bin.install "sc"
      bash_completion.install "completions/sc.bash" => "sc"
      zsh_completion.install "completions/sc.zsh" => "_sc"
      fish_completion.install "completions/sc.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://saucelabs.com/downloads/sauce-connect/5.0.1/sauce-connect-5.0.1_linux.aarch64.tar.gz"
      sha256 "567f57a95e78565cf5c879e14c704650cb5b54223eb676d940870a7fecff9f19"

      def install
        bin.install "sc"
        bash_completion.install "completions/sc.bash" => "sc"
        zsh_completion.install "completions/sc.zsh" => "_sc"
        fish_completion.install "completions/sc.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://saucelabs.com/downloads/sauce-connect/5.0.1/sauce-connect-5.0.1_linux.x86_64.tar.gz"
      sha256 "eddb0dad5275fd939d7bdb6dafd81ec1d30d198ad473bcd1ef5c8bb341eb39cf"

      def install
        bin.install "sc"
        bash_completion.install "completions/sc.bash" => "sc"
        zsh_completion.install "completions/sc.zsh" => "_sc"
        fish_completion.install "completions/sc.fish"
      end
    end
  end

  test do
    system "#{bin}/sc version"
  end
end
